// ============================================================
// Card Constants - Predefined function cards
// ============================================================

import { Card, CardEffectType } from '../types/card';

/** All available cards in the game */
export const ALL_CARDS: Card[] = [
  {
    id: 'card_shield',
    name: 'Khiên Thần',
    description: 'Tạo khiên bảo vệ hấp thụ 8 điểm sát thương trong 3 lượt',
    effectType: 'shield',
    rarity: 'rare',
    manaCost: 3,
    iconUrl: 'shield',
    effectAnimation: 'shield_activate',
    duration: 3,
    value: 8,
    price: 150,
    currencyType: 'gold',
    isOwned: false,
    quantity: 0,
    maxPerGame: 1,
    cooldownTurns: 5,
  },
  {
    id: 'card_heal',
    name: 'Hồi Sinh Mệnh',
    description: 'Hồi phục 10 điểm sinh mệnh',
    effectType: 'heal',
    rarity: 'common',
    manaCost: 2,
    iconUrl: 'heal',
    effectAnimation: 'heal_pulse',
    value: 10,
    price: 100,
    currencyType: 'gold',
    isOwned: false,
    quantity: 0,
    maxPerGame: 2,
    cooldownTurns: 4,
  },
  {
    id: 'card_double_damage',
    name: 'Song Sát',
    description: 'Nhân đôi sát thương gây ra trong 2 lượt tiếp theo',
    effectType: 'double_damage',
    rarity: 'epic',
    manaCost: 4,
    iconUrl: 'double_damage',
    effectAnimation: 'power_surge',
    duration: 2,
    value: 2,
    price: 80,
    currencyType: 'gems',
    isOwned: false,
    quantity: 0,
    maxPerGame: 1,
    cooldownTurns: 6,
  },
  {
    id: 'card_freeze',
    name: 'Băng Phong',
    description: 'Đóng băng 1 quân cờ đối thủ trong 2 lượt',
    effectType: 'freeze',
    rarity: 'rare',
    manaCost: 3,
    iconUrl: 'freeze',
    effectAnimation: 'freeze_blast',
    duration: 2,
    price: 200,
    currencyType: 'gold',
    isOwned: false,
    quantity: 0,
    maxPerGame: 1,
    cooldownTurns: 5,
  },
  {
    id: 'card_resurrect',
    name: 'Phục Sinh',
    description: 'Hồi sinh 1 quân cờ đã bị bắt (trừ Hậu)',
    effectType: 'resurrect',
    rarity: 'legendary',
    manaCost: 5,
    iconUrl: 'resurrect',
    effectAnimation: 'resurrect_beam',
    price: 200,
    currencyType: 'gems',
    isOwned: false,
    quantity: 0,
    maxPerGame: 1,
    cooldownTurns: 8,
  },
  {
    id: 'card_swap',
    name: 'Hoán Đổi',
    description: 'Hoán đổi vị trí 2 quân cờ của bạn',
    effectType: 'swap',
    rarity: 'rare',
    manaCost: 3,
    iconUrl: 'swap',
    effectAnimation: 'swap_portal',
    price: 180,
    currencyType: 'gold',
    isOwned: false,
    quantity: 0,
    maxPerGame: 2,
    cooldownTurns: 4,
  },
  {
    id: 'card_reveal',
    name: 'Thiên Nhãn',
    description: 'Hiển thị nước đi tiếp theo của đối thủ',
    effectType: 'reveal',
    rarity: 'epic',
    manaCost: 4,
    iconUrl: 'reveal',
    effectAnimation: 'eye_open',
    duration: 1,
    price: 120,
    currencyType: 'gems',
    isOwned: false,
    quantity: 0,
    maxPerGame: 1,
    cooldownTurns: 6,
  },
  {
    id: 'card_time_bonus',
    name: 'Thời Gian',
    description: 'Thêm 60 giây vào đồng hồ của bạn',
    effectType: 'time_bonus',
    rarity: 'common',
    manaCost: 1,
    iconUrl: 'time',
    effectAnimation: 'time_ripple',
    value: 60,
    price: 50,
    currencyType: 'gold',
    isOwned: false,
    quantity: 0,
    maxPerGame: 2,
    cooldownTurns: 3,
  },
  {
    id: 'card_poison',
    name: 'Kịch Độc',
    description: 'Gây 2 sát thương mỗi lượt trong 3 lượt cho đối thủ',
    effectType: 'poison',
    rarity: 'epic',
    manaCost: 4,
    iconUrl: 'poison',
    effectAnimation: 'poison_cloud',
    duration: 3,
    value: 2,
    price: 150,
    currencyType: 'gems',
    isOwned: false,
    quantity: 0,
    maxPerGame: 1,
    cooldownTurns: 7,
  },
  {
    id: 'card_mirror',
    name: 'Gương Phản Chiếu',
    description: 'Phản chiếu 50% sát thương nhận lại cho đối thủ trong 2 lượt',
    effectType: 'mirror',
    rarity: 'legendary',
    manaCost: 5,
    iconUrl: 'mirror',
    effectAnimation: 'mirror_shatter',
    duration: 2,
    value: 0.5,
    price: 250,
    currencyType: 'gems',
    isOwned: false,
    quantity: 0,
    maxPerGame: 1,
    cooldownTurns: 8,
  },
  {
    id: 'card_teleport',
    name: 'Dịch Chuyển',
    description: 'Di chuyển 1 quân cờ đến ô trống bất kỳ',
    effectType: 'teleport',
    rarity: 'legendary',
    manaCost: 5,
    iconUrl: 'teleport',
    effectAnimation: 'teleport_flash',
    price: 300,
    currencyType: 'gems',
    isOwned: false,
    quantity: 0,
    maxPerGame: 1,
    cooldownTurns: 10,
  },
  {
    id: 'card_fortify',
    name: 'Thành Trì',
    description: 'Tăng HP tối đa thêm 5 và hồi phục 5 HP',
    effectType: 'fortify',
    rarity: 'rare',
    manaCost: 3,
    iconUrl: 'fortify',
    effectAnimation: 'fortify_aura',
    value: 5,
    price: 120,
    currencyType: 'gold',
    isOwned: false,
    quantity: 0,
    maxPerGame: 1,
    cooldownTurns: 6,
  },
];

/** Rarity display config */
export const RARITY_CONFIG = {
  common: {
    label: 'Thường',
    color: '#9CA3AF',
    borderColor: 'rgba(156, 163, 175, 0.5)',
    glowColor: 'rgba(156, 163, 175, 0.3)',
  },
  rare: {
    label: 'Hiếm',
    color: '#3B82F6',
    borderColor: 'rgba(59, 130, 246, 0.5)',
    glowColor: 'rgba(59, 130, 246, 0.3)',
  },
  epic: {
    label: 'Sử Thi',
    color: '#A855F7',
    borderColor: 'rgba(168, 85, 247, 0.5)',
    glowColor: 'rgba(168, 85, 247, 0.3)',
  },
  legendary: {
    label: 'Huyền Thoại',
    color: '#F59E0B',
    borderColor: 'rgba(245, 158, 11, 0.5)',
    glowColor: 'rgba(245, 158, 11, 0.3)',
  },
} as const;
