export enum GameState {
  WAITING = 'WAITING',
  READY = 'READY',
  PLAYING = 'PLAYING',
  FINISHED = 'FINISHED',
  DISCONNECTED = 'DISCONNECTED',
  CANCELLED = 'CANCELLED',
  ABANDONED = 'ABANDONED',
  DRAW = 'DRAW'
}